sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f infrastructure/tools/Dockerfile .

script:
  - docker run travis-build infrastructure/tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  - docker run travis-build /bin/bash -c "CXX=clang++ ./waf configure build_debug --init build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "CXXFLAGS=-DDISABLE_LOGGER CXX=clang++ ./waf configure build_debug --init build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
